### ISSUE TITLE
Avatars are too small

### ISSUE THREAD

**Issue by SW1FT** [svenpaulsen/ts3client-improved-theme#1]
They should have the normal size imo.

**Comment by svenpaulsen** [comment]
Automatic resizing of avatars is controlled by these settings:

https://github.com/svenpaulsen/ts3client-improved-theme/blob/master/styles/improved/clientinfo.tpl#L16

I actually prefer smaller avatars so I don't think I'll change the default in this theme. In addition, TeamSpeak decided to use a version of this theme without the avatar resizing as their new default stylesheet in version 3.1.5 or later.
